# Configure the build process for Jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - src
  - public

# Build and deploy the Jekyll site to GitHub Pages
defaults:
  # Set default values for all documents of the site
  # You can change these values for each page or post individually
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: "/:path/"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:year/:month/:day/:title/"

# Configure the Node.js environment for running the React app
name: Node.js with React
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
      - name: Start Server
        run: npm start
        env:
          CI: false
